services:
  client:
    image: kasperhermansen/darklight-client
    ports:
      - 9081:3000

  server:
    image: kasperhermansen/darklight-server
    environment:
      FRONTEND_URL: https://darklight.front.kjuulh.io
      STORAGE_PATH: /mnt/storage
    ports:
      - 9082:8000
