services:
  client:
    build:
      context: client
    ports:
      - 3000:3000

  server:
    build:
      context: server
    environment:
      FRONTEND_URL: http://localhost:3000
      STORAGE_PATH: /mnt/storage
    ports:
      - 8000:8000

  nats:
    image: nats
    ports:
      - 4222:4222

  minio: 
    image: quay.io/minio/minio
    hostname: minio
    command: server /data --console-address ":9001"
    volumes:
    - "minio_data:/data"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ed4bdcaba3e4bed421b46cc4d3d3a5863b9a4826
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  crdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=example-single-node --logtostderr=WARNING --log-file-verbosity=WARNING --insecure
    ports:
      - "26257:26257"
      - "8080:8080"

  crdb-init:
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=darklight

volumes:
  minio_data: {}
  cockroach_data: {}
