[workspace]

members = [
    "darklight_api",
    "darklight_graphql",
    "darklight_ytd",
    "darklight_persistence",
    "darklight_core",
    "darklight_storage",
    "darklight_events",
    "darklight_handlers",
    "darklight_app",
    "darklight"
]